version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    env_file: .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - redis
    command: npm run start:dev
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
