# 개발용 도커파일

# Base Image
FROM node:18-alpine

ENV NODE_ENV=development

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json, package-lock.json 복사
COPY package*.json ./

# npm install
RUN npm install

# 소스코드 복사
COPY . .

# 빌드
RUN npm run build

# 포트 설정
EXPOSE 8000

# 실행
CMD ["npm", "run", "start:dev"]
